# Copia este archivo
# Cambia el nombre a "sonar-project.properties"
sonar.projectKey="tokenDeSonarqube"

# Comando a correr para el scanner
# 1. Levanta el servicio de Sonarqube
# 2. Ejecuta este comando:
# sonar-scanner   -Dsonar.projectKey=ProyectoGPIS   -Dsonar.sources=.   -Dsonar.host.url=http://localhost:9000   -Dsonar.token=tokenDeSonarqube